name: 'Configure China Mirrors'
description: 'Configure npm and pip to use China mirrors for faster downloads'
runs:
  using: 'composite'
  steps:
    - name: Configure npm China mirror
      shell: bash
      run: |
        echo "Configuring npm to use China mirrors..."
        npm config set registry https://registry.npmmirror.com/
        # Set Electron mirror via environment variables instead of npm config
        echo "ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/" >> $GITHUB_ENV
        echo "ELECTRON_BUILDER_BINARIES_MIRROR=https://npmmirror.com/mirrors/electron-builder-binaries/" >> $GITHUB_ENV
        echo "npm registry configured"
        
    - name: Configure pip China mirror  
      shell: bash
      run: |
        echo "Configuring pip to use China mirrors..."
        mkdir -p ~/.pip
        cat > ~/.pip/pip.conf << EOF
        [global]
        index-url = https://pypi.tuna.tsinghua.edu.cn/simple/
        trusted-host = pypi.tuna.tsinghua.edu.cn
        timeout = 120
        EOF
        echo "pip mirror configured"
