name: Setup Fast Environment
description: "Quick environment setup for fast checks"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Create and Setup Virtual Environment
      shell: bash
      working-directory: ./backend
      run: |
        echo "⚡ 创建虚拟环境并安装依赖..."

        # 创建虚拟环境（如果不存在）
        if [ ! -d ".venv" ]; then
          echo "📦 创建虚拟环境..."
          python -m venv .venv
        else
          echo "✅ 虚拟环境已存在"
        fi

        # 激活虚拟环境并安装依赖
        source .venv/bin/activate
        echo "📥 安装必要的Python依赖..."
        pip install --upgrade pip wheel
        pip install flake8==6.0.0 django-debug-toolbar==4.2.0 django-extensions==3.2.3 || echo "部分依赖安装失败，继续执行"

        echo "✅ 虚拟环境设置完成"
