# 生产环境优化配置 - 针对内存受限服务器（1.7GB）
# 使用方式: docker-compose -f docker-compose.prod-optimized.yml up -d

services:
  # MySQL - 内存优化配置
  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME:-bravo}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-bravo_prod_2024}
      MYSQL_DATABASE: ${DB_NAME:-bravo_production}
      MYSQL_USER: ${DB_USER:-bravo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-bravo_pass_2024}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --max_connections=50
      --innodb_buffer_pool_size=128M
      --innodb_log_file_size=32M
      --performance_schema=OFF
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
    restart: unless-stopped

  # Redis - 轻量配置
  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-bravo}-redis
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 50M
    restart: unless-stopped

  # Django后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: ${COMPOSE_PROJECT_NAME:-bravo}-backend
    environment:
      - DJANGO_SETTINGS_MODULE=bravo.settings.production
      - DB_NAME=${DB_NAME:-bravo_production}
      - DB_USER=${DB_USER:-bravo}
      - DB_PASSWORD=${DB_PASSWORD:-bravo_pass_2024}
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DISABLE_SSL_REDIRECT=True
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      # staticfiles在容器内构建，不需要挂载
      # - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
      - staticfiles:/app/staticfiles # 使用named volume在frontend间共享
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
    restart: unless-stopped

  # Celery Worker - 轻量配置
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: ${COMPOSE_PROJECT_NAME:-bravo}-celery
    command: sh -c "mkdir -p /var/log/django && chmod 777 /var/log/django && celery -A bravo worker -l warning --concurrency=1"
    environment:
      - DJANGO_SETTINGS_MODULE=bravo.settings.production
      - DB_NAME=${DB_NAME:-bravo_production}
      - DB_USER=${DB_USER:-bravo}
      - DB_PASSWORD=${DB_PASSWORD:-bravo_pass_2024}
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M
    restart: unless-stopped

  # Vue前端 + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: ${COMPOSE_PROJECT_NAME:-bravo}-frontend
    ports:
      - "${FRONTEND_HTTP_PORT:-80}:80"
      - "${FRONTEND_HTTPS_PORT:-443}:443"
    volumes:
      - staticfiles:/usr/share/nginx/html/static:ro # 从backend共享，只读
      - ./backend/media:/usr/share/nginx/html/media
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  staticfiles: # 用于backend和frontend共享静态文件
