# GitHub Actions 完全模拟器
# 创建一个完全独立的容器环境，模拟推送到PR时触发的所有工作流

version: "3.8"

services:
  github-actions-simulator:
    build:
      context: .
      dockerfile: Dockerfile.github-actions-simulator
    container_name: bravo-github-actions-simulator
    environment:
      - CI=true
      - GITHUB_ACTIONS=true
      - PYTHONUNBUFFERED=1
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=bravo_test
      - DB_USER=bravo_user
      - DB_PASSWORD=bravo_password
      - DJANGO_SETTINGS_MODULE=bravo.settings.test
    volumes:
      # 创建可写的工作目录
      - github_actions_workspace:/workspace
    working_dir: /workspace
    command: ["/run_github_actions_simulation.sh"]
    # 分配足够的资源
    mem_limit: 4g
    cpus: 2.0

volumes:
  github_actions_workspace:
