# 生产环境优化配置 - 针对内存受限服务器（1.7GB）
# 使用方式: docker-compose -f docker-compose.prod-optimized.yml up -d

services:
  # MySQL - 内存优化配置
  mysql:
    image: mysql:8.0
    container_name: bravo-mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-bravo_prod_2024}
      MYSQL_DATABASE: ${DB_NAME:-bravo_production}
      MYSQL_USER: ${DB_USER:-bravo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-bravo_pass_2024}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --max_connections=50
      --innodb_buffer_pool_size=128M
      --innodb_log_file_size=32M
      --query_cache_size=0
      --performance_schema=OFF
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
    restart: unless-stopped

  # Redis - 轻量配置
  redis:
    image: redis:7-alpine
    container_name: bravo-redis-prod
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 50M
    restart: unless-stopped

  # Django后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: bravo-backend-prod
    environment:
      - DJANGO_SETTINGS_MODULE=bravo.settings.production
      - DATABASE_URL=mysql://${DB_USER:-bravo}:${DB_PASSWORD:-bravo_pass_2024}@mysql:3306/${DB_NAME:-bravo_production}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M
    restart: unless-stopped

  # Celery Worker - 轻量配置
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: bravo-celery-prod
    command: celery -A bravo worker -l warning --concurrency=1
    environment:
      - DJANGO_SETTINGS_MODULE=bravo.settings.production
      - DATABASE_URL=mysql://${DB_USER:-bravo}:${DB_PASSWORD:-bravo_pass_2024}@mysql:3306/${DB_NAME:-bravo_production}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M
    restart: unless-stopped

  # Vue前端 + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: bravo-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/staticfiles:/usr/share/nginx/html/static
      - ./backend/media:/usr/share/nginx/html/media
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
