# Bravo 开发工具配置
# 可选的开发辅助工具
# 使用方式: docker-compose -f docker-compose.yml -f docker-compose.tools.yml up

services:
  # 工具服务 - Mailhog (邮件测试)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: bravo-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - default
    restart: unless-stopped

  # 工具服务 - MinIO (S3 兼容存储)
  minio:
    image: minio/minio:latest
    container_name: bravo-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - default
    restart: unless-stopped

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: bravo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - default
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
