# Generated by Django 4.2.7 on 2025-12-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        help_text="需要验证的邮箱地址", max_length=255, verbose_name="验证邮箱"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="邮箱验证的唯一令牌",
                        max_length=255,
                        unique=True,
                        verbose_name="验证令牌",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="验证令牌的过期时间", verbose_name="过期时间"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="邮箱验证完成的时间",
                        null=True,
                        verbose_name="验证时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="记录创建的时间", verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "邮箱验证",
                "verbose_name_plural": "邮箱验证",
                "db_table": "users_email_verification",
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(
                        help_text="密码重置的唯一令牌",
                        max_length=255,
                        unique=True,
                        verbose_name="重置令牌",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="重置令牌的过期时间", verbose_name="过期时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="密码重置令牌被使用的时间",
                        null=True,
                        verbose_name="使用时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="记录创建的时间", verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "密码重置",
                "verbose_name_plural": "密码重置",
                "db_table": "users_password_reset",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                blank=True,
                help_text="用户头像的URL地址",
                max_length=500,
                null=True,
                verbose_name="头像URL",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="用户的显示名称，用于前端展示",
                max_length=100,
                null=True,
                verbose_name="显示名称",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="邮箱验证完成的时间", null=True, verbose_name="邮箱验证时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="连续登录失败的次数", verbose_name="登录失败次数"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(
                default=False, help_text="标识用户邮箱是否已验证", verbose_name="邮箱是否验证"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="账户锁定到期时间，超过此时间后账户自动解锁",
                null=True,
                verbose_name="锁定到期时间",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_email_verified"], name="idx_email_verified"),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="user",
            field=models.ForeignKey(
                help_text="关联的用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                help_text="关联的用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["token"], name="idx_pwd_reset_token"),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["user"], name="idx_pwd_reset_user"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["token"], name="idx_email_verify_token"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["user", "email"], name="idx_email_verify_user"),
        ),
    ]
