# Generated by Django 4.2.7 on 2025-12-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailverification_passwordreset_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="用户邮箱地址，必须唯一", max_length=254, unique=True, verbose_name="邮箱"
            ),
        ),
    ]
