name: Setup Cached Environment
description: "Fast environment setup with aggressive caching"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js with Cache
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"
        cache-dependency-path: |
          package-lock.json
          frontend/package-lock.json
          e2e/package-lock.json

    - name: Setup Python with Cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: "backend/requirements/*.txt"

    - name: Restore Full Dependency Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
          ~/.cache/pip
          backend/.venv
        key: full-deps-v4-${{ runner.os }}-${{ hashFiles('**/package-lock.json', 'backend/requirements/*.txt') }}
        restore-keys: |
          full-deps-v4-${{ runner.os }}-

    - name: Install Missing Dependencies
      shell: bash
      run: |
        echo "🚀 检查并安装缺失依赖..."

        # 检查根依赖
        if [ ! -d "node_modules" ]; then
          echo "安装根依赖..."
          npm ci --prefer-offline --no-audit
        fi

        # 前端依赖通过根目录npm workspaces管理
        echo "✅ Frontend dependencies managed via root npm workspaces"

        # 检查后端依赖 - 修复缓存问题：检查关键包是否存在
        cd backend
        if [ ! -d ".venv" ]; then
          echo "🆕 创建虚拟环境..."
          python -m venv .venv
          NEED_INSTALL=true
        else
          echo "🔍 检查现有虚拟环境中的关键依赖..."
          source .venv/bin/activate
          # 检查django_extensions是否存在（这是最常失败的包）
          if ! python -c "import django_extensions" 2>/dev/null; then
            echo "❌ django_extensions缺失，需要重新安装依赖"
            NEED_INSTALL=true
          else
            echo "✅ 关键依赖存在，跳过安装"
            NEED_INSTALL=false
          fi
        fi

        if [ "$NEED_INSTALL" = "true" ]; then
          echo "📦 安装/更新后端依赖..."
          source .venv/bin/activate
          pip install --upgrade pip wheel

          # 🔧 修复编码问题：强制使用UTF-8编码读取requirements文件
          export PYTHONIOENCODING=utf-8
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8

          echo "📦 安装requirements（强制UTF-8编码）..."
          pip install -r requirements/base.txt -r requirements/test.txt
        fi
        cd ..

        echo "✅ 依赖检查完成"

    - name: Save Full Dependency Cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          node_modules
          ~/.cache/pip
          backend/.venv
        key: full-deps-v4-${{ runner.os }}-${{ hashFiles('**/package-lock.json', 'backend/requirements/*.txt') }}
